# Generated by Django 2.0.3 on 2018-04-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180412_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
