# Generated by Django 2.0.3 on 2018-04-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180420_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='ubuntu-debian.jpg', null=True, upload_to=''),
        ),
    ]
