# Generated by Django 2.0.3 on 2018-04-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/noimages.jpg', upload_to=''),
        ),
    ]
