# Generated by Django 2.0.3 on 2018-04-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20180420_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to=''),
        ),
    ]
