# Generated by Django 2.0.3 on 2018-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20180423_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to=''),
        ),
    ]
